name: Front End Test Cases
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v4
 
     - name: Cypress Setup
       uses: cypress-io/github-action@v6

     - name: Run Cypress Tests
       run: |
         cd ./client
         npm install cypress
         npm run build
         npm start